spring:
  application:
    name: gateway-simple
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #\u6CE8\u518C\u5230nacos\u4E2D
    gateway: # \u6839\u636E\u670D\u52A1\u540D\u8F6C\u53D1\u8DEF\u7531
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true # \u5C06\u670D\u52A1\u540D\u6539\u4E3A\u5C0F\u5199\uFF0C\u9ED8\u8BA4\u90FD\u662F\u5927\u5199\u7684
server:
  port: 80

# \u914D\u7F6E \u8DEF\u7531\u8FFD\u8E2A\u65E5\u5FD7\u6253\u5370
logging:
  level:
    root: info
    org.springframework.web.servlet.DispatcherServlet: debug
    org.springframework.cloud.sleuth: debug

